let a:number = 6;
let b:number = 2;
console.log(a+b);
let c:number = 10;
let d:number = 2;
console.log(c-d);
let addition:number = 6 + 2;
console.log("addition",addition);
let sub:number = 10 - 2;
console.log("subtraction $ (sub)");
let multiplication:number = 4 * 2;
console.log("multipilication",multiplication);
let division:number = 16/2;
console.log("Division",division);